# Generated by Django 3.2.9 on 2021-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1500)),
                ('uuid', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
